//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.02 at 10:51:58 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.springbyexample.org/schema/beans")
package org.springbyexample.schema.beans;
