DROP TABLE ADDRESS IF EXISTS;
DROP TABLE PERSON IF EXISTS;

CREATE TABLE PERSON (
    ID integer identity primary key,  
    FIRST_NAME varchar(50) not null,
    LAST_NAME varchar(50) not null,
	CREATED timestamp,
	CONSTRAINT IDX_PERSON_ID PRIMARY KEY (ID)
);

CREATE TABLE ADDRESS (
    ID integer identity primary key,
    PERSON_ID integer,  
    ADDRESS varchar(255),
    CITY varchar(50) not null,
    STATE varchar(50) null,
    ZIP_POSTAL varchar(30) not null,
	COUNTRY varchar(50) not null,
	CREATED timestamp,
    CONSTRAINT IDX_ADDRESS_ID PRIMARY KEY (ID),
    CONSTRAINT FK_ADDRESS_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID) on delete cascade
);

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(1, 'Joe', 'Smith', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(1, 1, '1060 West Addison St.', 'Chicago', 'IL', '60613', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(2, 'John', 'Wilson', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(2, 2, '2 Penn Plz # 15', 'New York', 'NY', '10121', 'USA', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(3, 2, '47 Howard St.', 'San Francisco', 'CA', '94103', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(3, '길동', '홍', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(4, 3, '강남구 삼성동 무역센터 코엑스', '서울시', null, '135-731', '대한민국', NOW());


INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(4, 'John', 'Whorfin', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(5, 4, '', 'Grover Mills', 'New Jersey', '', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(5, 'John', 'Bigboote', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(6, 5, '', 'Grover Mills', 'New Jersey', '', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(6, 'John', 'Parker', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(7, 6, '', 'Grover Mills', 'New Jersey', '', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(7, 'John', 'O''Connor', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(8, 7, '', 'Grover Mills', 'New Jersey', '', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(8, 'John', 'Emdall', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(9, 8, '', 'Grover Mills', 'New Jersey', '', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(9, 'John', 'Yaya', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(10, 9, '', 'Grover Mills', 'New Jersey', '', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(10, 'John', 'Gomez', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(11, 10, '', 'Grover Mills', 'New Jersey', '', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(11, 'Bruce', 'Wayne', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(12, 11, '1007 Mountain Drive', 'Gotham', '', '', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(12, 'Clark', 'Kent', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(13, 12, '1938 Sullivan Place', 'Metropolis', '', '', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(13, 'Hal', 'Jordan', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(14, 13, '', 'Coast City', 'CA', '', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(14, 'Billy', 'Batson', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(15, 14, '', 'Fawcett City', 'IN', '', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(15, 'Hank', 'McCoy', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(16, 15, '1407 Graymalkin Lane', 'Salem Center', 'NY', '', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(16, 'Bobby', 'Drake', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(17, 16, '1407 Graymalkin Lane', 'Salem Center', 'NY', '', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(17, 'Scott', 'Summers', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(18, 17, '1407 Graymalkin Lane', 'Salem Center', 'NY', '', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(18, 'Jean', 'Grey', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(19, 18, '1407 Graymalkin Lane', 'Salem Center', 'NY', '', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(19, 'Stephen', 'Strange', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(20, 19, '177A Bleecker Street', 'New York', 'NY', '10012', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(20, 'Steve', 'Rogers', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(21, 20, '890 Fifth Avenue', 'New York', 'NY', '10021', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(21, 'Janet', 'Van Dyne', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(22, 21, '890 Fifth Avenue', 'New York', 'NY', '10021', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(22, 'Henry', 'Pym', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(23, 22, '890 Fifth Avenue', 'New York', 'NY', '10021', 'USA', NOW());

INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, CREATED) 
   VALUES(23, 'Tony', 'Stark', NOW());
INSERT INTO ADDRESS(ID, PERSON_ID, ADDRESS, CITY, STATE, ZIP_POSTAL, COUNTRY, CREATED) 
   VALUES(24, 23, '890 Fifth Avenue', 'New York', 'NY', '10021', 'USA', NOW());
