/* DO NO EDIT THIS FILE MANUALLY IT IS GENERATED AUTOMATICALLY BY ../build/build.sh */
 this.ExtSpecs = [
    'spec/class/Class.js',
    'spec/class/ClassManager.js',
    'spec/Date.js',
    'spec/dom/CompositeElementLite.js',
    'spec/dom/DomHelper.js',
    'spec/dom/Element.insertion.js',
    'spec/dom/Element.js',
    'spec/dom/Element.static.js',
    'spec/dom/Element.style.js',
    'spec/dom/Element.traversal.js',
    'spec/EventManager.js',
    'spec/Ext-more.js',
    'spec/Ext.js',
    'spec/lang/Array.js',
    'spec/lang/Date.js',
    'spec/lang/Error.js',
    'spec/lang/Function.js',
    'spec/lang/Number.js',
    'spec/lang/Object.js',
    'spec/lang/String.js',
    'spec/misc/JSON.js',
    'spec/Support.js',
    'spec/util/Format.js',
    'spec/version/Version.js'
];
